"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("scalts-array");
var Serializable_1 = require("./core/Serializable");
exports.Serializable = Serializable_1.default;
var Serialize_1 = require("./decorators/Serialize");
exports.Serialize = Serialize_1.default;
var SerializeOpt_1 = require("./decorators/SerializeOpt");
exports.SerializeOpt = SerializeOpt_1.default;
var SerializeArray_1 = require("./decorators/SerializeArray");
exports.SerializeArray = SerializeArray_1.default;
var UnmarshallError_1 = require("./errors/UnmarshallError");
exports.UnmarshallError = UnmarshallError_1.default;
